// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsbnbnbyrjjwoejtgduy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzYm5ibmJ5cmpqd29lanRnZHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Njc1NTQsImV4cCI6MjA2OTA0MzU1NH0.zNIFHbZkps9vMsUcZUTKY-R3ZYmc9NETPAdoZQT4BpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});